FROM python:3.7.10-alpine3.12 

RUN apk add --no-cache gcc g++ musl-dev python3-dev libffi-dev openssl-dev cargo git libxml2-dev libxslt-dev libgcrypt-dev libressl-dev postgresql postgresql-dev

COPY src/requirements.txt /opt/Yearning/src/requirements.txt  

RUN  pip3 install -r /opt/Yearning/src/requirements.txt \
	&& sed -i "s#\(.*\)int(self\.server_version\.split('\.', 1)\[0\]) >= 5\(.*\)#\1int(self\.server_version\.split('\.', 1)\[0\]) >= 5 or self\.server_version\.split('\.', 1)\[0\] == 'Inception2'\2#g" /usr/local/lib/python3.7/site-packages/pymysql/connections.py \
	&& sed -i "/defer_warnings/{n;s#self\._show_warnings()#pass#g}" /usr/local/lib/python3.7/site-packages/pymysql/cursors.py
COPY src /opt/Yearning/src

WORKDIR /opt/Yearning/src 
RUN mv deploy.conf.template deploy.conf

COPY install/docker-entrypoint.sh ./docker-entrypoint.sh
RUN chmod 0755 ./docker-entrypoint.sh

ENTRYPOINT ["./docker-entrypoint.sh"]


EXPOSE 8000

STOPSIGNAL SIGTERM

CMD [ "gunicorn","-c","gunicorn.conf", "settingConf.wsgi:application" ]
