# Generated by Django 2.0.1 on 2018-11-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sqlorder_exceuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqlorder',
            name='delete_yn',
            field=models.IntegerField(default=1),
        ),
    ]
