# Generated by Django 2.0.1 on 2019-08-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20181212_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='from_ldap',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='databaselist',
            name='dbtype',
            field=models.CharField(default='mysql', max_length=50),
        ),
        migrations.AddField(
            model_name='databaselist',
            name='has_repl_perm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='databaselist',
            name='has_super_perm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='databaselist',
            name='is_slave',
            field=models.BooleanField(default=False),
        ),
    ]
