# Generated by Django 2.0.1 on 2019-08-28 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190827_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaselist',
            name='delete_yn',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='query_order',
            name='delete_yn',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='todolist',
            name='delete_yn',
            field=models.IntegerField(default=1),
        ),
    ]
