version: '2'

services:
  db:
    container_name: mysql
    image: mysql:5.7
    # ports:
    #  - 3306:3306
    volumes:
      - /server/docker_share/mysql:/var/lib/mysql
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - ./etc/mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=root
    network_mode: bridge
    restart: always

  inception:
    container_name: goinception
    image: hanchuanchuan/goinception:v1.2.3
    ports:
      - 4000:4000
    volumes:
      - ./etc/goinception/config.toml:/etc/config.toml
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    network_mode: bridge
    restart: always
    links:
      - db

  yearning:
    container_name: yearning
    image: registry.cn-beijing.aliyuncs.com/donobody/yearning
    build: 
      context: ..
      dockerfile: ./Dockerfile-src
    depends_on: 
      - db
      - inception
    ports:
      - "8000:8000"
    environment:
      HOST: 0.0.0.0
      MYSQL_PASSWORD: root
      MYSQL_USER: root
      MYSQL_ADDR: db
    network_mode: bridge
    restart: always
    links:
      - db
      - inception
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
  
  yearningweb:
    container_name: yearningweb
    build:
      context: ..
      dockerfile: ./Dockerfile-webpage
    image: registry.cn-beijing.aliyuncs.com/donobody/yearningweb
    depends_on: 
      - yearning
    network_mode: bridge
    restart: always
    ports:
      - 80:80
    links:
      - yearning
    volumes:
      - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    environment:
      - NODE_ENV=production

