version: '2'

services:
  db:
    container_name: mysql
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - d://workspace/docker_share/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    container_name: mysql
    command:
      mysqld --sql_mode="NO_AUTO_VALUE_ON_ZERO,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION,PIPES_AS_CONCAT,ANSI_QUOTES"
    network_mode: bridge
    restart: always

  inception:
    container_name: inception
    image: registry.cn-hangzhou.aliyuncs.com/lihuanhuan/inception
    ports:
      - 6669:6669
    volumes:
      - d://workspace/github/Yearning/install/etc/inception/inc.cnf:/etc/inc.cnf
    network_mode: bridge
    restart: always
    container_name: inception
    restart: always

  yearning:
    container_name: yearning
    image: registry.cn-beijing.aliyuncs.com/donobody/yearning
    build: 
      context: ..
      dockerfile: ./Dockerfile-src
    depends_on: 
      - db
      - inception
    ports:
      - "8000:8000"
    environment:
      HOST: localhost
      MYSQL_PASSWORD: yearning
      MYSQL_USER: root
      MYSQL_ADDR: db
    network_mode: bridge
    restart: always
  
  yearningweb:
    container_name: yearningweb
    build:
      context: ..
      dockerfile: ./Dockerfile-webpage
    image: registry.cn-beijing.aliyuncs.com/donobody/yearningweb
    depends_on: 
      - yearning
    network_mode: bridge
    restart: always
    ports:
      - 80:80

